name: Rust Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          export PATH="$HOME/.cargo/bin:$PATH"
          rustup default stable

      - name: Build and Test hello
        run: |
          cd chapter02/hello
          cargo build --verbose
          cargo test --verbose

      - name: Build and Test actix-gcd
        run: |
          cd chapter02/actix-gcd
          cargo build --verbose
          cargo test --verbose

